### ISSUE TITLE
ums-8.0.0-1b8d9bc shows audio files only in transcode folder

### ISSUE THREAD

**Issue by felsen2011** [UniversalMediaServer/UniversalMediaServer#1743]
Tested with *.mp3; *.oga and *.flac

Renderconfig for Samsumg-JU6400 identical in 7.7.1 and 8.0.0

INFO  2019-01-04 00:03:39.048 [main] Starting Universal Media Server 8.0.0-b1
INFO  2019-01-04 00:03:39.049 [main] Based on PS3 Media Server by shagrath, copyright 2008-2014
INFO  2019-01-04 00:03:39.050 [main] https://www.universalmediaserver.com
INFO  2019-01-04 00:03:39.050 [main]
INFO  2019-01-04 00:03:39.050 [main] Build: 1b8d9bc3a (2019-01-03)
INFO  2019-01-04 00:03:39.051 [main] Java: OpenJDK Client VM 1.8.0_191 (32-bit) by Oracle Corporation
INFO  2019-01-04 00:03:39.054 [main] OS: Linux 32-bit 4.14.87-153
INFO  2019-01-04 00:03:39.066 [main] Maximum JVM Memory: 742.4 MiB
INFO  2019-01-04 00:03:39.091 [main] Language: German
INFO  2019-01-04 00:03:39.091 [main] Encoding: UTF-8

DEBUG 2019-01-04 11:57:06.007 [HTTPv2 Request Worker 1] Recognized media renderer "[TV] UE48JU6450"
DEBUG 2019-01-04 11:57:06.025 [HTTPv2 Request Worker 1] Setting bookmark for [...]2010 - Tron Legacy/CD2/Daft Punk - Tron- Legacy - 01 - Encom Part I.flac => 0
DEBUG 2019-01-04 11:57:06.029 [HTTPv2 Request Worker 1] Setting bookmark for [...]2010 - Tron Legacy/CD2/Daft Punk - Tron- Legacy - 02 - Encom Part II.flac => 0
DEBUG 2019-01-04 11:57:06.032 [HTTPv2 Request Worker 1] Setting bookmark for [...]2010 - Tron Legacy/CD2/Daft Punk - Tron- Legacy - 03 - Round One.flac => 0
DEBUG 2019-01-04 11:57:06.036 [HTTPv2 Request Worker 1] Setting bookmark for [...]2010 - Tron Legacy/CD2/Daft Punk - Tron- Legacy - 04 - Castor.flac => 0
DEBUG 2019-01-04 11:57:06.040 [HTTPv2 Request Worker 1] Setting bookmark for [...]2010 - Tron Legacy/CD2/Daft Punk - Tron- Legacy - 05 - Reflections.flac => 0
DEBUG 2019-01-04 12:01:35.936 [HTTPv2 Request Worker 7] Setting bookmark for [...]2013 - Random Access Memories/Cover.jpg => 0 /* Picture File gets listed as only file in the folder */
DEBUG 2019-01-04 12:01:35.940 [HTTPv2 Request Worker 7] Setting bookmark for [...]2013 - Random Access Memories/Daft Punk - Random Access Memories - 01 - Give Life Back to Music.mp3 => 0
DEBUG 2019-01-04 12:01:35.944 [HTTPv2 Request Worker 7] Setting bookmark for [...]2013 - Random Access Memories/Daft Punk - Random Access Memories - 02 - The Game of Love.mp3 => 0
DEBUG 2019-01-04 12:01:35.947 [HTTPv2 Request Worker 7] Setting bookmark for [...]2013 - Random Access Memories/Daft Punk - Random Access Memories - 03 - Giorgio by Moroder.mp3 => 0
DEBUG 2019-01-04 12:01:35.952 [HTTPv2 Request Worker 7] Setting bookmark for [...]2013 - Random Access Memories/Daft Punk - Random Access Memories - 04 - Within.mp3 => 0
DEBUG 2019-01-04 12:01:35.956 [HTTPv2 Request Worker 7] Setting bookmark for [...]2013 - Random Access Memories/Daft Punk - Random Access Memories - 05 - Instant Crush (feat. Julian Casablancas).mp3 => 0
DEBUG 2019-01-04 12:01:35.959 [HTTPv2 Request Worker 7] Setting bookmark for [...]2013 - Random Access Memories/Daft Punk - Random Access Memories - 06 - Lose Yourself to Dance (feat. Pharrell Williams).mp3 => 0
DEBUG 2019-01-04 12:01:35.964 [HTTPv2 Request Worker 7] Setting bookmark for [...]2013 - Random Access Memories/Daft Punk - Random Access Memories - 07 - Touch (feat. Paul Williams).mp3 => 0
DEBUG 2019-01-04 12:01:35.968 [HTTPv2 Request Worker 7] Setting bookmark for [...]2013 - Random Access Memories/Daft Punk - Random Access Memories - 08 - Get Lucky (feat. Pharrell Williams).mp3 => 0
DEBUG 2019-01-04 12:01:35.971 [HTTPv2 Request Worker 7] Setting bookmark for [...]2013 - Random Access Memories/Daft Punk - Random Access Memories - 09 - Beyond.mp3 => 0
DEBUG 2019-01-04 12:01:35.975 [HTTPv2 Request Worker 7] Setting bookmark for [...]2013 - Random Access Memories/Daft Punk - Random Access Memories - 10 - Motherboard.mp3 => 0
DEBUG 2019-01-04 12:01:35.978 [HTTPv2 Request Worker 7] Setting bookmark for [...]2013 - Random Access Memories/Daft Punk - Random Access Memories - 11 - Fragments of Time (feat. Todd Edwards).mp3 => 0
DEBUG 2019-01-04 12:01:35.982 [HTTPv2 Request Worker 7] Setting bookmark for [...]2013 - Random Access Memories/Daft Punk - Random Access Memories - 12 - Doin' It Right (feat. Panda Bear).mp3 => 0
DEBUG 2019-01-04 12:01:35.986 [HTTPv2 Request Worker 7] Setting bookmark for [...]2013 - Random Access Memories/Daft Punk - Random Access Memories - 13 - Contact.mp3 => 0
DEBUG 2019-01-04 12:01:35.989 [HTTPv2 Request Worker 7] Setting bookmark for [...]2013 - Random Access Memories/Daft Punk - Random Access Memories - 14 - Horizon.mp3 => 0

**Comment by felsen2011** [comment]
I will try to get a TRACE output tomorrow ... didn't have it set unfortunately.

**Comment by felsen2011** [comment]
Example for library scanner trace, seems to be identical for all audio files.
Currently root node listing fails so I can't test directory listing for audio files, will try again later.

TRACE 2019-01-05 08:09:29.641 [Library Scanner] Adding new child "3 Doors Down - The Better Life - 04 - Not Enough.mp3" with class "RealFile"
TRACE 2019-01-05 08:09:29.641 [Library Scanner] Getting player for resource "3 Doors Down - The Better Life - 04 - Not Enough.mp3"
TRACE 2019-01-05 08:09:29.641 [Library Scanner] Player "FFmpeg Video" is incompatible
TRACE 2019-01-05 08:09:29.641 [Library Scanner] Player "MEncoder Video" is incompatible
TRACE 2019-01-05 08:09:29.641 [Library Scanner] Player "tsMuxeR Video" isn't available
TRACE 2019-01-05 08:09:29.642 [Library Scanner] Player "VLC Video" isn't available
TRACE 2019-01-05 08:09:29.642 [Library Scanner] Returning compatible player "FFmpeg Audio"
TRACE 2019-01-05 08:09:29.642 [Library Scanner] Matched support line f:.+
TRACE 2019-01-05 08:09:29.642 [Library Scanner] Final verdict: "3 Doors Down - The Better Life - 04 - Not Enough.mp3" will be streamed
TRACE 2019-01-05 08:09:29.642 [Library Scanner] Matched support line f:.+
TRACE 2019-01-05 08:09:29.642 [Library Scanner] File "3 Doors Down - The Better Life - 04 - Not Enough.mp3" will be sent with MIME type "MIMETYPE_AUTO"
TRACE 2019-01-05 08:09:29.643 [Library Scanner] Adding "3 Doors Down - The Better Life - 04 - Not Enough.mp3" to transcode folder for player: "null"

**Comment by valib** [comment]
@felsen2011 please follow the instruction https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556 and send the full info. Seems like your TV is not properly recognized.

**Comment by valib** [comment]
@felsen2011 I understand that you don't want to share your file structure but what you provided doesn't help. For the testing please set shared folder to the one you can share and follow the instruction.

**Comment by felsen2011** [comment]
Problem persists in official Beta1 Release.

Minimal testcase debug log:
[debug.log.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2752921/debug.log.txt)

**Comment by valib** [comment]
@felsen2011 please try this conf.

[Samsung-JU6400.conf.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2753662/Samsung-JU6400.conf.txt)

**Comment by felsen2011** [comment]
Problem remains

[UMS-8.0.0b1-testsetup-26-01-2019-12-30.log.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2798928/UMS-8.0.0b1-testsetup-26-01-2019-12-30.log.txt)

**Comment by felsen2011** [comment]
Problem still exists in RC1

Videos work fine in every way.
Audio files are only listed in transcode folders.

I deleted the media database prior to this test to get a fresh start.

[UMS-8.0.0-RC1-testsetup-23-02-2019-16-49.log.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2896961/UMS-8.0.0-RC1-testsetup-23-02-2019-16-49.log.txt)

**Comment by SubJunk** [comment]
@felsen2011 thanks for the update. Can you try in the web interface please? Also did it work in the past, and if so which version?

**Comment by felsen2011** [comment]
@subjunk
Web Interface works just fine.

It did and does work with all versions of the 7.x branch (7.9.0 yet untested) on all tested devices.
It never did work with the 8.x branch on my Samsung TV.

**Comment by felsen2011** [comment]
Quick test of 7.9.0 with my live system on the Samsung TV: audio file listing working and playback starts w/o problems

**Comment by SubJunk** [comment]
@felsen2011 can you please try this version? I fixed a problem with audio files but not yours specifically, but it would be nice to see if it affected your issue. https://www.spirton.com/uploads/UMS/UMS-8.0.0-e366470.tgz
Also since your are using Linux I recommend checking if there are updates for MediaInfo since UMS v8 is designed to work best with the latest version

**Comment by felsen2011** [comment]
@SubJunk The behaviour as seen by my TV is still the same.
[UMS-8.0.0-e366470-03-03-2019-11-21.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2922998/UMS-8.0.0-e366470-03-03-2019-11-21.txt)

Current mediainfo version of Ubuntu 18.04 armhf (which I am using a derivative of) is:
17.12-1
Unfortunately package builds for arm platforms are always a little behind current developments ...
Therefore I have compiled my own version of mediainfo 18.12. but with no changes in behaviour either.

**Comment by SubJunk** [comment]
I have confirmed that MP3 files work on my TV in 8.0.0 so it must be something quite specific.

You have provided us with some nice logs for 8.0.0 that show what we send to your TV but we don't have that for the one that works (v7), please provide that for comparison

**Comment by felsen2011** [comment]
@SubJunk 
Log of the same testsetup with working UMS 7.9.0:
[UMS-7.9.0-testsetup-17-03-2019-13-35.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2975134/UMS-7.9.0-testsetup-17-03-2019-13-35.log)

**Comment by SubJunk** [comment]
@felsen2011 thanks a lot, I'm comparing them now

**Comment by SubJunk** [comment]
Ok I see we have a bug with our file support recognition in v8 which will need to be fixed, which means it is being transcoded when it shouldn't be. I'm working on that now

**Comment by SubJunk** [comment]
Ok I think there are two issues here. One is the old MediaInfo version, and the other is the renderer configuration file... that's my current theory anyway.
Can you try manually updating MediaInfo from https://mediaarea.net/en/MediaInfo/Download/Ubuntu ? You might also need to recreate the database/cache if you have that enabled

**Comment by SubJunk** [comment]
@felsen2011 sorry for the spam but as a follow up I'm interested to know whether you are willing to test https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1774 if I make a test for it. That would help a lot and would prevent this kind of bug

**Comment by felsen2011** [comment]
@SubJunk I wouldn't have started this thread if I wasn't willing to help ;)
Just to clarify ... I am using UMS on a small one single board computer with an arm core.
Therefore I need all software compiled for "armhf". Thats also the reason why I cannot use tie standard repositories such as https://mediaarea.net/en/MediaInfo/Download/Ubuntu
I tried to manually compile and install the newest MediaInfo but apparently the installation part failed as UMS is still using the old one. Have to take a look into that.

**Comment by SubJunk** [comment]
@felsen2011 I see, thanks for clarifying. In that case, until you can get MediaInfo updated, the second fix that I hope will work is to replace the renderer config file with https://github.com/UniversalMediaServer/UniversalMediaServer/blob/4c78121e06bb7cc41946e5267cf18570af6f1b59/src/main/external-resources/renderers/Samsung-JU6400.conf

**Comment by felsen2011** [comment]
I managed to compile and install the 18.12  libmediainfo shared object but didn't improve things:
[UMS-8.0.0RC1-testsetup-mediainfo1812-31-03-2019-16-35.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/3026709/UMS-8.0.0RC1-testsetup-mediainfo1812-31-03-2019-16-35.log)

UMS 7.9.0 still works with the new libmediainfo.

UMS 8.0.0 RC1 works with the new renderer config \o/

**Comment by felsen2011** [comment]
UMS 8.0.1 Working out of the box
