### ISSUE TITLE
10.8.0 Fails to start UMS

### ISSUE THREAD

**Issue by mbentley** [UniversalMediaServer/UniversalMediaServer#2575]
Starting with 10.8.0, I can't start UMS any longer.  If I roll back to 10.7.0, it starts fine.

```
...
INFO  00:42:34.440 [main] Using address /172.17.0.8 found on network interface: name:eth0 (eth0)
INFO  00:42:34.440 [main] Created socket: /172.17.0.8:5001
INFO  00:42:34.570 [main] Web interface is available at: http://172.17.0.8:9001
INFO  00:42:34.601 [main] A tiny cache admin interface is available at: http://172.17.0.8:5001/console/home
ERROR 00:42:34.807 [main] A serious error occurred during Universal Media Server initialization: null
```

Full log output:  [ums_log.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/6871672/ums_log.txt)

Trace logs: [debug.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/6871676/debug.log)

I have a few Docker images that this can be reproduced with, based on both Debian 10 (Buster) and Alpine Linux 3.14:

`docker run -it --rm mbentley/ums:10-alpine`

`docker run -it --rm mbentley/ums:10`

**Comment by SubJunk** [comment]
@mbentley thanks for reporting this, I am in the process of publishing a fix now, and will post here when it's pushed

**Comment by SubJunk** [comment]
@mbentley that should be fixed now, please let me know if there are any other problems

**Comment by Krakinou** [comment]
Had same issue with 10.8.0, updated to 10.8.1 and still have the same issue :/
Running on a debian buster.
I can provide the log if required but they are similar to those of mbentley.

**Comment by Jermolinski** [comment]
I have the same problem too.
It looks like, that enabled buffered logging doesn't have a timer to write log entries into the log file in case the log data is smaller than 8K.
It leads to the missing log entries in the log file. If the buffered logging is switched off, a null exception will be logged too:

ERROR 2021-07-24 13:29:49.407 [main] A serious error occurred during Universal Media Server initialization: null
DEBUG 2021-07-24 13:29:49.408 [main] 
java.lang.NullPointerException: null
	at net.pms.dlna.RootFolder.loadWebConf(RootFolder.java:475)
	at net.pms.dlna.RootFolder.discoverChildren(RootFolder.java:189)
	at net.pms.dlna.RootFolder.discoverChildren(RootFolder.java:117)
	at net.pms.configuration.RendererConfiguration.getRootFolder(RendererConfiguration.java:488)
	at net.pms.PMS.getRootFolder(PMS.java:163)
	at net.pms.PMS.init(PMS.java:723)
	at net.pms.PMS.createInstance(PMS.java:942)
	at net.pms.PMS.main(PMS.java:1108)

Here is the full log file:
[ums.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/6872366/ums.log)

**Comment by mbentley** [comment]
I do see the same behavior with 10.8.1 as well.

```
# docker run -it --rm mbentley/ums:10-alpine
INFO  12:09:14.314 [entrypoint] ownership is correct on '/opt/ums/UMS.conf'
INFO  12:09:14.324 [entrypoint] ownership is correct on '/opt/ums/data'
INFO  12:09:14.335 [entrypoint] ownership is correct on '/opt/ums/database'
INFO  12:09:14.339 [entrypoint] Removing old FIFOs (if they exist)
INFO  12:09:14.342 [entrypoint] Adding '/opt/ums/linux' to the PATH
INFO  12:09:14.343 [entrypoint] Launching command '/opt/ums/UMS.sh' as user ums
INFO  12:09:15.082 [main] Language not specified, defaulting to OS language.
INFO  12:09:15.316 [main] Starting Universal Media Server 10.8.1
INFO  12:09:15.316 [main] Based on PS3 Media Server by shagrath, copyright 2008-2014
INFO  12:09:15.316 [main] https://www.universalmediaserver.com
...
INFO  12:09:17.319 [main] Transcoding engine "tsMuxeR Audio" is available
INFO  12:09:17.320 [main] Transcoding engine "VLC Web Audio (Legacy)" is available
INFO  12:09:17.320 [main] Transcoding engine "VLC Web Video (Legacy)" is available
WARN  12:09:17.323 [main] Transcoding engine "DCRaw" is not available
INFO  12:09:17.323 [main] Transcoding engine "youtube-dl" is available
INFO  12:09:17.325 [main] Using address /172.17.0.8 found on network interface: name:eth0 (eth0)
INFO  12:09:17.326 [main] Created socket: /172.17.0.8:5001
INFO  12:09:17.463 [main] Web interface is available at: http://172.17.0.8:9001
INFO  12:09:17.497 [main] A tiny cache admin interface is available at: http://172.17.0.8:5001/console/home
ERROR 12:09:17.705 [main] A serious error occurred during Universal Media Server initialization: null
```

**Comment by Nadahar** [comment]
> It looks like, that enabled buffered logging doesn't have a timer to write log entries into the log file in case the log data is smaller than 8K.

There's no timer - I'm not sure exactly how that would work. However, UMS is supposed to flush the buffer when shutting down, my guess is that the crash leads to the shutdown code never being run. That's always the problem with buffering, when things crash unexpectedly, you don't get the chance to flush - the same would have been true for a timer.

If you run UMS in "trace mode" (either by selecting "Restart in trace mode" (or whatever the string is) from the GUI or by adding `trace` as a command line option, several settings will be forced to "maximum traceability" including disabling buffered logging for that session. In that way, there's no need to change the configuration as long as you need the "trace mode" when troubleshooting.

**Comment by SubJunk** [comment]
@Krakinou @Jermolinski @mbentley can you please provide logs from 10.8.1 in trace mode?

**Comment by SubJunk** [comment]
I have reproduced this now and am working on a fix. Will update this thread when it's published

**Comment by SubJunk** [comment]
The fix is published now

**Comment by Krakinou** [comment]
Solve it for me. UMS starts without issue.
Tx!

**Comment by mbentley** [comment]
^ Same.  Thanks!

**Comment by Jermolinski** [comment]
According to the recent changes in the source code, the error should be corrected now.
But, the https://www.fosshub.com/Universal-Media-Server.html still points to the old version 10.8.1, where the error still persists.
The build from the actual source code fails too:
[ums.build.errors.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/6873979/ums.build.errors.txt)

**Comment by SubJunk** [comment]
It will be on FossHub in about an hour but for now feel free to get it from https://sourceforge.net/projects/unimediaserver/files/10.8.2/
I'm not sure why that build error happened for you though, we were seeing that on CI at one point too
