### ISSUE TITLE
Update folder contents when thumbnail is updated

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#2664]
I realised that my comment on #2599 might have been forgotten being on a closed issue

I found that on PS4 that it will not reload a folder until the contents of that folder has changed, that means if a file is marked as played the PS4 does not see any change and does not display the updated thumbnail

A solution would be to say that the contents has changed when the thumbnail is updated

**Comment by SubJunk** [comment]
We have another report of this https://github.com/UniversalMediaServer/UniversalMediaServer/issues/4608

**Comment by SubJunk** [comment]
In v14 we added GENA broadcasting of the SystemUpdateId property, which should fix this for some renderers, but unfortunately not for PS4.

One idea I have for PS4 is to start using the containerUpdateId as described on page 39 of https://upnp.org/specs/av/UPnP-av-ContentDirectory-v4-Service.pdf

We can't know whether PS4 will use that value until we try, but it is a good idea anyway

**Comment by Fredo1650** [comment]
Hello, I confirm that the bug is still present on version 14, do you have any solutions to correct this ?

**Comment by SubJunk** [comment]
@Fredo1650 it's more a bug or missing feature on PS4 than our bug. I know that doesn't help you but it might explain why I'm not treating it with more urgency.

It might be possible for us to fix this as described above, or the PS4 might still ignore that attempt, because it is already ignoring all of our existing attempts to say the content was updated

In 14.1 we have a new strategy added for audio files updates so it is a step closer to doing that for video files too, so we are moving towards it

**Comment by Fredo1650** [comment]
Hello, on the UMS 14.5.0 version I still have this problem of updating the thumbnails entirely marked on the Samsung QLED 2023 TQ43Q68CAU TV
The images below are between the Samsung TV and the UMS WEB player we see that on the TV no thumbnail is marked / updated, but on the WEB player it works well.
Thank you.
![Capture d’écran 2024-09-25 000423](https://github.com/user-attachments/assets/1bbd945e-452d-4e61-a05f-9d0a1b3a3bdc)
![20240925_000334](https://github.com/user-attachments/assets/f752160f-123a-48dc-9ad2-cd6746947afc)
![Capture d’écran 2024-09-25 000453](https://github.com/user-attachments/assets/074e40a5-8a26-4698-8648-df3896d6bb76)
![20240925_000352](https://github.com/user-attachments/assets/c27f3f2e-a7cf-4188-9896-3bb06352b2b4)

**Comment by SurfaceS** [comment]
There is 2 things :

First is fully playing data are user aware, so if the TV is not using the same UMS user than the browser, it is normal that it do not has the same thumbs.

Second is UMS's UPnP tell the TV that the item was updated, but the TV keep the old thumb.
I'll have a look on this.

**Comment by Fredo1650** [comment]
Hello, the second explanation is the most likely, because all the videos were viewed on the television, and I find these same videos which are marked on the WEB player but not on the television.

I did another test with another older Samsung TV (UE40D6500) I find the videos marked as on the WEB player.
I think it uses the old thumbnails and does not update them when it becomes marked fully read on these new TVs
Can UMS force the thumbnail update?

Thank you.

**Comment by SubJunk** [comment]
Please try this attempted fix and let us know how it goes
https://www.universalmediaserver.com/uploads/UMS-2664.exe
And please let me know when you have downloaded it so I can remove it from the server

**Comment by Fredo1650** [comment]
Hello, thank you very much for this fix, I downloaded and installed the "UMS-2664.exe" version, I watched the entire video 8 on the TV, the thumbnail marking on the TV still does not work with this version, on the WEB player the video is marked as in the images below.
[ums_dbg_2024-09-28-02-51.zip](https://github.com/user-attachments/files/17171755/ums_dbg_2024-09-28-02-51.zip)

![20240928_025135](https://github.com/user-attachments/assets/55923a3b-42fd-4746-85aa-4632d739e060)
![Capture d’écran 2024-09-28 014600](https://github.com/user-attachments/assets/00b9d18c-4ed2-4525-8201-772df359c539)

**Comment by SurfaceS** [comment]
@Fredo1650 
Can you try to use the new DIDL Lite engine ?
On the web interface, settings, services, check the "JUPnP DIDL Lite (beta)".

The old (default) DIDL Lite engine will be updated as well on the next release.

**Comment by Fredo1650** [comment]
Hello, I used the JUPnp DIDL Lite services with (UMS-2664.exe), it still does not work I have done some tests with a Test file I see that when the thumbnails are displayed for the first time the TV links them with the name of the file and does not change state even if I delete the file and put it back, the thumbnail will be displayed in the state it was in the first time even if it marked play. On UMS I did another test to manually mark a new file, then the TV finds this new file and displays the marked thumbnail but then impossible to return it to its original state.
Thank you.

[ums_dbg_2024-09-28-22-35.zip](https://github.com/user-attachments/files/17176606/ums_dbg_2024-09-28-22-35.zip)

**Comment by Fredo1650** [comment]
On the UMS forum I came across the Post "Samsung Q9 Series Problems" this topic looks exactly like the problem I'm currently having with thumbnails.
https://www.universalmediaserver.com/forum/viewtopic.php?t=14768

**Comment by SurfaceS** [comment]
@Fredo1650 

I see that this time it use updateid for thumbs URL.
So it solve the web browser update (no refresh needed), and should solve the TV as well.

> I see that when the thumbnails are displayed for the first time the TV links them with the name of the file and does not change state even if I delete the file and put it back, the thumbnail will be displayed in the state it was in the first time even if it marked play.

That is a normal situation, as playing state can be kept a little bit until db clean (that will check if the file exists).
So if you put back the file, it can get back the status.

> On UMS I did another test to manually mark a new file, then the TV finds this new file and displays the marked thumbnail but then impossible to return it to its original state.

Playing state "ISFULLYPLAYED" is permanent even if you restart the media. So it is a normal behavior.

To unset the "ISFULLYPLAYED" for a media:
On the web interface (with the same user as TV if needed), browse player, go to the media you want to unset like on this image (in French for you)

![image](https://github.com/user-attachments/assets/e24837e9-457f-43a9-b0b3-f212d82261a4)

**Comment by Fredo1650** [comment]
Hello, thanks for your reply but the problem is that the TV does not update the new thumbnail marked as read.
All videos are played with the TV and are all marked as read on the UMS WEB player so it is the same user as in the images below.
But I think the TV remembers the original state of the thumbnail and does not update when UMS marks them as read.
As mentioned in my previous post another user had this kind of problem also on the Post "Samsung Q9 Series Problems" on the forum.
In my test I manually marked the videos <ISFULLYPLAYED> in the WEB player, but the TV does not update the marked thumbnail.
Do you have a solution to force the TV to update? 
Thank you.
![Capture d’écran 2024-09-29 211842](https://github.com/user-attachments/assets/e7d180db-8b29-46b9-bf0b-efcab6ecdfc6)
![Capture d’écran 2024-09-29 211905](https://github.com/user-attachments/assets/b7d438e9-6ef6-4e29-adba-fe43fae705fb)
![20240929_211722](https://github.com/user-attachments/assets/957d83b3-1a83-414e-b1a4-f7c041296307)
![20240929_211740](https://github.com/user-attachments/assets/7b786808-91ad-4d3d-ba71-cdaacb1b3ba2)

**Comment by Mik-S-UMS** [comment]
Is there any change if you copy another video into that folder? I found that the PS4 would only refresh the thumbnails if the folder contents changed.

**Comment by SurfaceS** [comment]
@Mik-S-UMS 
> Is there any change if you copy another video into that folder? I found that the PS4 would only refresh the thumbnails if the folder contents changed.

I think this is not the same issue.
Your issue (PS4) should be handled in #4998.

This issue seems to be a Samsung TV issue.
It does save the thumbnail for an object id, then it never load it again.
As I understand, you can restart UMS and the TV, it give the saved thumb.

**Comment by SurfaceS** [comment]
**Tested on 2021 Samsung TV so far :**
With `SystemUpdateID` and `ObjectUpdateID` changed between 2 request.

Changing thumb` URI query` with the ObjectUpdateID -> fail
Changing thumb `URI completely` -> fail
HTTP header `Cache-Control: no-cache` -> fail
Adding HTTP header `ETag` with `If-None-Match` handle -> fail
Changing `ObjectUpdateID` to the UPnP (v4) response -> fail
Changing `res.UpdateCount` to the UPnP (v4) response -> fail

**Comment by Fredo1650** [comment]
Hello, @Mik-S-UMS 
I have already done this test but it does not change anything.
@SurfaceS
Yes, that's exactly the problem, I've already turned off the TV completely by disconnecting it electrically but it still doesn't update after restarting.
The TV always remains on the same thumbnail as when it was first seen, and does not change state.

**Comment by SubJunk** [comment]
I'll build and upload it soon

**Comment by Fredo1650** [comment]
@SurfaceS
Hello, thank you very much for your work and to the UMS team too, for this solution, I can't wait to try it on the TV when this new version is released.

**Comment by SubJunk** [comment]
@Fredo1650 you can test it at https://www.universalmediaserver.com/uploads/UMS-2664.exe
Please let me know when you have downloaded it so I can remove it

**Comment by Fredo1650** [comment]
Hello, I have just tested this new version UMS-2664 / UMS 14.6.0 it works perfectly well thank you very much to the whole team for solving this problem.

@SubJunk You can delete this file it works very well the thumbnails are updated each time. Thank you very much

**Comment by SubJunk** [comment]
@Fredo1650 thank you for all your testing!
