### ISSUE TITLE
x64 installer not working on Windows 10

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#5211]
This is related to a comment on Patreon:

> Tested Windows x86_64 on Win10 22H2 bare metal and on a VM. Both simply do not start, tried updating and fresh install, Task manager shows nothing.

> Standard x86 works fine on both.

I have no idea why that would be happening. I am running it on Windows 11. I downloaded the build from Patreon and installed it, and it continued to work for me. Does anyone have any ideas?

**Comment by Mik-S-UMS** [comment]
I did have an issue installing 14.8.0 after using the build script. 

It did not install the bin files into `C:\Program Files\Universal Media Server\` and I could not run UMS from there. 
The only way I could get it to run is with the UMS.bat file.
It also left the old `C:\Program Files (x86)\Universal Media Server\` folder alone.

Doing a clean install made it work properly but still have the old folder. 

I did not have a problem upgrading to 14.9.0 afterwards so may have something to do with the change in installation location, or may have just been because I was using that script instead of the official installer.

@SubJunk does that build script create the x86_64 installer? If not do I need to change anything for it to make this one?

**Comment by SurfaceS** [comment]
> It also left the old C:\Program Files (x86)\Universal Media Server\ folder alone.

This need to be done if moving... I forgot that.

**Comment by SubJunk** [comment]
@SurfaceS will you fix it? I can skip the x64 version in the auto updater and website for now to minimize the impact

**Comment by SubJunk** [comment]
I have stopped UMS from updating to the x64 installer now, in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/5212
I am making the same change to the website now, then I will remove the installer from the release post, until the problems are fixed.

**Comment by SurfaceS** [comment]
> @SurfaceS will you fix it? I can skip the x64 version in the auto updater and website for now to minimize the impact

fixed

**Comment by SubJunk** [comment]
Apparently it is not fixed, I posted this fix to Patreon and a user said:

> server doesn't launch by itself after installation even if it was checked. Tried open it manually, but it doesn't work. I reboot the pc and the server launch itself but with the 14.8.0 version :/

**Comment by SubJunk** [comment]
@SurfaceS I forgot to tag you in the above post

**Comment by SubJunk** [comment]
I have tested and my directory `C:\Program Files (x86)\Universal Media Server\` is still there after installing too

**Comment by SurfaceS** [comment]
@SubJunk wait a bit for release as you updated the binaries.

**Comment by SurfaceS** [comment]
fix is ready, I'll test most scenario and PR it.

**Comment by SurfaceS** [comment]
@SubJunk it is ready to merge.
It should fix all the points.

**Comment by SubJunk** [comment]
It works for me, I have uploaded it to Patreon for more feedback

**Comment by Mik-S-UMS** [comment]
I think there is still an issue with the new installer.

When I installed UMS on a virgin system it did not run afterwards and looking at the installation folder there was no `bin` folder either (and another one, I think `jre17` but can't remember. There was only 3 instead of 5 folders).
Running the installer again did fix it so that may be why some have said it now works for them.

This was from using the build script so I don't know if the main release has this problem.

I'll have to do a reinstall of the OS on this computer soon as it was done on the wrong drive (SATA SSD instead of NVME) and setup the user account properly so I'll be able to test again. 
Not in any rush though as I'm still putting it though it paces making everything is working good. 

I'm hoping that I can just detach the SSD to install Win11 on the NVME and then reattach it to access the files I already downloaded so I don't need to download them again, but not sure with this secure boot in Win 11 if it encrypts everything so will be unable to read a previous install drive. I have some research to do before I attempt it.

**Comment by SubJunk** [comment]
Ah cool, good idea to test it again fresh. I have seen that happen before too but like you said, it always fixes itself the second time

**Comment by Mik-S-UMS** [comment]
I did a bit more testing once I reinstalled win 11.

The first run does not install the bin and other folder (I forgot to check it again) but the second run will install these.

I used the uninstaller and rebooted but found the the there were still some remnants left behind like 
`C:\Program Files\Universal Media Server\renderers`
`C:\ProgramData\UMS`
      (I understand that these may want to be kept just in case)
and in the start menu but without the icons.
![Image](https://github.com/user-attachments/assets/b33a3da4-10c1-43cc-a1e7-2d826da943f2)

I deleted these, reinstalled to confirm it acts the same, then uninstalled again and removed these folders.

As a test I created the empty `C:\Program Files\Universal Media Server` folder myself then installed UMS. 
This time everything installed correctly first time.

I think there is some check that is missing to install these bin files if this folder does not exist, like if updating from an install in 
`C:\Program Files (x86)\Universal Media Server`
It works on the second install as this folder exists.

**Comment by Mik-S-UMS** [comment]
Maybe there is more to this than just the install folder. 
I had to take the computer back to the shop as windows was not activating so they did another fresh OS install so I had another clean slate.

This time I created the `C:\Program Files\Universal Media Server` folder first then installed UMS, but this time it did not install `bin` or `jre17` like before.
I noticed when running the installer the second time it said that the install type was an update when I don't remember it saying this the first time. There might be something missing from the first install the the update fixes.

**Comment by SurfaceS** [comment]
@Mik-S-UMS 
Should be fixed in #5328 
Be sure to use the `UMS-x86_64.exe` as the 32 bit is produced as well.

> I used the uninstaller and rebooted but found the the there were still some remnants left behind like
> C:\Program Files\Universal Media Server\renderers
> C:\ProgramData\UMS
> (I understand that these may want to be kept just in case)
> and in the start menu but without the icons.
I added a remove of the `C:\ProgramData\UMS` directory.
Maybe the choice can be left to the user (that want to keep it), but it is not implemented.

About `C:\Program Files\Universal Media Server\renderers`, that mean someone (a dev) add a renderer conf without adding it to the list to be removed from nsis, or the user create his own under this folder instead of the `C:\ProgramData\UMS\renderers` one (user renderer's conf).
If you have the name of the file(s) left on `C:\Program Files\Universal Media Server\renderers` after an uninstall, I can adjust the nsis script.

**Comment by Mik-S-UMS** [comment]
I can't remember if I added a new conf in that folder but its a possibility, but might not have as I had not been using it very long.
However all the renderer confs were still present in the renderer folder when I checked it.

I forgot that renderer confs can be loaded from `ProgramData`. 
I know there have been issues in the past with UMS not loading them from here so I usually suggest users copy new confs to 
`C:\Program Files\Universal Media Server\renderers` while I am troubleshooting for them.
I should probably tell them to use `C:\ProgramData\UMS\renderers` from now on.

**Comment by SurfaceS** [comment]
`C:\ProgramData\UMS\renderers` for system install
`C:\Users\XXX\AppData\Local\UMS\renderers` for user install
`XXX\portable\renderers` for portable install
