### ISSUE TITLE
Back button not always working on web

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#5548]
Sometimes on the web interface when I'm browsing, using the back button doesn't work. Clicking the breadcrumb seems to always work though

**Comment by Mik-S-UMS** [comment]
I have noticed this for a while whenever I tested the web player going back many versions. I hardly use it so assumed it was just my mouse misreading my click on the back mouse button.

This is on Firefox so I don't know if it happens on other web browsers.

**Comment by SubJunk** [comment]
This has been fixed

**Comment by Mik-S-UMS** [comment]
I don't think it has. I just ran a fresh build and it is still happening to me and seems to happen more consistently now.
I have to hit back twice before it will react but then have to click forward once to get back to the series list.

https://github.com/user-attachments/assets/2e51bf4b-3190-4de7-9c18-78f7e187e03e

**Comment by SubJunk** [comment]
Oh I tested it before closing this, maybe I didn't do the right thing

**Comment by Mik-S-UMS** [comment]
I checked on another browser (Brave) and it does the same thing.
It seems to be ignoring the first press after clicking on a link, after that it works normally going back and forward.

It only seems to happen on the player, on the settings it works as it should.

I do vaguely remember this happening in V14 or even earlier too but not sure. 
I always use the back/forward buttons on the mouse so might have thought it was a miss-click and pressed it again without thinking.
