### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by si70so15** [UniversalMediaServer/UniversalMediaServer#5727]
HI,
today when I try to build application with the last source code, I receive this error code :

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:33 min
[INFO] Finished at: 2025-09-01T18:50:57+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:3.1.0:run (process-resources-windows) on project ums: An Ant BuildException has occured: Can't get https://www.universalmediaserver.com/binaries/win32/dcrawMS.exe to D:\Progetti\GitHub\UniversalMediaServer\target\bin\windows\dcrawMS.exe
[ERROR] around Ant part ...<get usetimestamp="true" src="https://www.universalmediaserver.com/binaries/win32/dcrawMS.exe" dest="D:\Progetti\GitHub\UniversalMediaServer/target/bin/windows/dcrawMS.exe" />... @ 22:180 in D:\Progetti\GitHub\UniversalMediaServer\target\antrun\build-main.xml
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Even after resetting the entire repository, when I build the application as the instruction, I still get the following error (see attached log file)

[Build log.txt](https://github.com/user-attachments/files/22083428/Build.log.txt)

**Comment by si70so15** [comment]
Hi,
I'm not sure if I posted my previous message in the right place, but I'm asking for help to understand whether I'm making a mistake in building the application.
I’m attaching two additional log files to help clarify the issue I’m experiencing.
Please let me know if you need any further details or if there's a more appropriate place to submit this kind of request.
Thank you for your support!

[TEST-net.pms.encoders.FFmpegVideoTest.xml](https://github.com/user-attachments/files/22125834/TEST-net.pms.encoders.FFmpegVideoTest.xml)

[net.pms.encoders.FFmpegVideoTest.txt](https://github.com/user-attachments/files/22125836/net.pms.encoders.FFmpegVideoTest.txt)

**Comment by SubJunk** [comment]
@si70so15 hi, we were having some infrastructure problems at that time that I think explains that problem. It should be better now

**Comment by si70so15** [comment]
@SubJunk Hi,
I tried to build after your post, but when I attempt to build the UMS, I still encounter a problem during the test phase.
In particular, I encountered an error while running "net.pms.encoders.FFmpegVideoTest", which fails with the following exception: "java.lang.NullPointerException: Cannot invoke net.pms.io.OutputConsumer.join(long) because this.stderrConsumer is null". Additionally, the methods "net.pms.encoders.FFmpegVideoTest.testHardcodingSubtitles" and "net.pms.encoders.FFmpegVideoTest.testDolbyVisionOutput" also fail with the error: "java.lang.NullPointerException: Cannot invoke java.util.List.iterator() because ffmpegOutput is null".
I have also attach the full log of build.
Thank you

[UMS BuildLog 07-09-2025.txt](https://github.com/user-attachments/files/22197508/UMS.BuildLog.07-09-2025.txt)

**Comment by Maverynthia** [comment]
Still broken
[ERROR] Errors:
[ERROR]   FFmpegVideoTest.testDolbyVisionOutput:115 NullPointer Cannot invoke "java.util.List.iterator()" because "ffmpegOutput" is null
[ERROR]   FFmpegVideoTest.testHardcodingSubtitles:156 NullPointer Cannot invoke "java.util.List.iterator()" because "ffmpegOutput" is null

**Comment by SubJunk** [comment]
I have reproduced this now by clearing my cache, I will fix it soon

**Comment by SubJunk** [comment]
I think that is fixed now, please let me know

**Comment by si70so15** [comment]
> I think that is fixed now, please let me know

Everything's going fine for me now.

Thank you

**Comment by Mik-S-UMS** [comment]
I'm getting a build error too, this time `unable to find valid certification path to requested target`

```
[INFO]       [get] Error getting https://download.bell-sw.com/java/17.0.16+12/bellsoft-jre17.0.16+12-windows-amd64.zip to C:\Users\Mik\Downloads\UMSBuilder-1.10.0\Code\target\jre17-x64.zip
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:04 min
[INFO] Finished at: 2025-10-21T00:55:41+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:3.1.0:run (process-resources-windows) on project ums: An Ant BuildException has occured: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[ERROR] around Ant part ...<get usetimestamp="true" src="https://download.bell-sw.com/java/17.0.16+12/bellsoft-jre17.0.16+12-windows-amd64.zip" dest="C:\Users\Mik\Downloads\UMSBuilder-1.10.0\Code/target/jre17-x64.zip" />... @ 68:198 in C:\Users\Mik\Downloads\UMSBuilder-1.10.0\Code\target\antrun\build-main.xml
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
The system cannot find the file specified.
A duplicate file name exists, or the file
cannot be found.
```
I renamed the code folder so a new one will be downloaded but still happens.

**Comment by valib** [comment]
@SubJunk I have the same error.

**Comment by SubJunk** [comment]
That one might be fixed with this PR, I changed the source for that archive https://github.com/UniversalMediaServer/UniversalMediaServer/pull/5833
